### PR TITLE
disable the full UX flow test until PR 101 lands

### PR DESCRIPTION
**Pull request by rhelmer**

### CODE REVIEW

**Review by Carla-Moz — COMMENTED** [review]
Tests are still failing on my local which I'm not sure why since they passed in CircleCi. Can you see if you can reproduce on your end? I'm sure I'm on the right branch and have the latest. 

`FAIL tests/integration/ux.test.ts (10.753 s)
  Rally Web Platform extension interop
    ✕ fails to sign up for a new email account with invalid info (3091 ms)
    ✕ fails to sign into website with invalid email credentials (2326 ms)
    ✓ signs up for website with valid email credentials (2644 ms)
    ✕ fails to sign into website with invalid credentials (2009 ms)

  ● Rally Web Platform extension interop › fails to sign up for a new email account with invalid info

    InvalidArgumentError: binary is not a Firefox executable

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:517:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:642:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:568:28)`

**Comment by rhelmer** [comment]
> Tests are still failing on my local which I'm not sure why since they passed in CircleCi. Can you see if you can reproduce on your end? I'm sure I'm on the right branch and have the latest.
> 
> `FAIL tests/integration/ux.test.ts (10.753 s)
> Rally Web Platform extension interop
> ✕ fails to sign up for a new email account with invalid info (3091 ms)
> ✕ fails to sign into website with invalid email credentials (2326 ms)
> ✓ signs up for website with valid email credentials (2644 ms)
> ✕ fails to sign into website with invalid credentials (2009 ms)
> 
> ● Rally Web Platform extension interop › fails to sign up for a new email account with invalid info
> 
> ```
> InvalidArgumentError: binary is not a Firefox executable
> 
>   at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:517:15)
>   at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:642:13)
>   at Executor.execute (node_modules/selenium-webdriver/lib/http.js:568:28)`
> ```

Hm, which OS is this? Do you have Firefox Nightly installed? I can improve that error message, one moment.

**Comment by rhelmer** [comment]
@Carla-Moz oh actually you know what, per our conversation earlier today we don't really need to use Firefox Nightly anymore, that is leftover from when we needed special privileges in the core add-on. I'll just make the test use the standard Firefox release, that should be less hassle.

**Review by Carla-Moz — APPROVED** [review]
Looks good on my end!

**Pull request merged**
