### PR TITLE
UX fixes/changes for sidenav and account settings

### PR DESCRIPTION
**Pull request by thomik-corp**
* Make top nav links same as https://rally.mozilla.org/ i.e. underline on hover

* Account options should be to the left:
- Manage Profile
- Account Settings

* Main account settings should feel centered

* Account settings need to have hover state along with sub options e.g. Delete Account

* For active page we need bolder text (without link) and persistent gray background

* Manage profile should not turn blue (on hover text-decoration: none)

Hover state for menus:
image

Hover state for sub-menus:
image

Active sub-menu:
image

Centered account settings:
image

### CODE REVIEW

**Comment by jepstein** [comment]
2560px display - Account Settings doesn't looked centered. Is there a design for this wide?

Screen Shot 2022-06-01 at 10 34 06 AM

**Comment by tangcasey** [comment]
@jepstein @thomik-corp caught this last week and he's been working on it

**Comment by thomik-corp** [comment]
Made it centered and did my best to align columns. The issue is that our classes are colliding with bootstrap classes!

image

**Comment by tangcasey** [comment]
@jepstein @thomik-corp and I had talked about this –– the side nav should be left-aligned to the Mozilla logo left edge –– but there is a clash in which the page is built out. Ashish has told me, that once we move to bootstrap, this will not happen.

**Pull request merged**
