### PR TITLE
Apply responsiveness to RWP (nav, signin, privacy, survey)

### LINKED ISSUE #243: Apply responsiveness to RWP (nav, signin, privacy, survey)
- [x] Navbar: made the navbar responsive for all relevant screen sizes
- [x] Sign-in page 
- [x] Privacy/Term page
- [x] Demographic survey

Update: this ticket has been updated to better reflect the work I've completed 

PR: https://github.com/mozilla-rally/rally-web-platform/pull/280

### PR DESCRIPTION
**Pull request by Carla-Moz**
Closes #243 
In this PR, the signin cards, navbar, onboarding pages for privacy/terms and the demographic survey are made responsive with css-grid and flexbox. I've also removed the pop-up for google to have users continue with google within the same page. 

Next steps are having design review the components for the screen sizes which will likely lead to another responsive PR. I didn't want to overwhelm with one huge massive styles PR. 

Also looks like my new responsive styles broke one of the ux tests so will also investigate. 

Updated storybook: [RWP Storybook](http://localhost:6006/?path=/story/example-introduction--page)

### CODE REVIEW

**Comment by rhelmer** [comment]
> Also looks like my new responsive styles broke one of the ux tests so will also investigate.

I think the test failure is just the switch from `signInWithPoup` to `signInWithRedirect` (which looks great btw!), this whole part here is waiting for the pop-up to open, switching to that window, interacting, and switching back, which could be simplified now:

https://github.com/mozilla-rally/rally-web-platform/blob/bf6c357533833d3318cb8e39c80965688bd06211/tests/integration/ux.test.ts#L111-L137

**Review by rhelmer — COMMENTED** [review]
This looks much better on a smaller screen, but completing all the various tasks (join/leave, account settings etc) is pretty cramped on a smaller screen (iPhone 12 Pro dimensions used here via Chrome devtools):

image
image
image
image
image
image
image

**Review by rhelmer — COMMENTED** [review]
I find the way the menu behavior changes when going across the CSS breakpoint from the hamburger menu button to the user icon a little jarring, the only thing I've found that is really a bug per se is that there's no way to dismiss the menu if you:

1. click the hamburger menu while the window is smaller image then leaving the menu open, and
2. expand the browser window horizontally so the control changes from the "X" to the user icon. I can't figure out how to dismiss the menu now, unless I resize the window to be smaller again:
image

**Review by rhelmer — COMMENTED** [review]
I think this isn't necessarily new (the pop-up have this same behavior but it's more noticeable with the redirect) - after completing login with the Google sign-in redirect, the sign-in page is shown again briefly, before the redirect to the studies page happens.

This is relatively minor, but I bet there's a way to deal with this in the UI using the SDK, maybe by disabling the login fields and making it look inactive etc. until the `signInWithRedirect` either resolves or rejects.

I think users on slower connections are more likely to see this, and may try to interact with the sign-in page while the auth provider response is still pending.

**Comment by Carla-Moz** [comment]
Hi Rob, yes the studies page, authenticated profile pages and privacy pages haven't be worked on yet. Only the nav, sign-in, onboarding privacy and terms pages. I will fix the bugs on the nav! Thank you!

**Review by rhelmer — APPROVED** [review]

**Review by tangcasey — APPROVED** [review]
Approved for merge

**Pull request merged**
